DROP DATABASE IF EXISTS musiclovers;   
CREATE DATABASE IF NOT EXISTS musiclovers;   
USE musiclovers;

CREATE TABLE IF NOT EXISTS albums
(
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) UNIQUE NOT NULL,
  genre VARCHAR(255) NOT NULL,
  picture VARCHAR(255) NOT NULL,
  artist VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tracks
(
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(128) UNIQUE NOT NULL,
  youtube_url VARCHAR(255) NOT NULL,
  id_album INTEGER NOT NULL,
  CONSTRAINT fk_album
    FOREIGN KEY (id_album) 
        REFERENCES albums(id)
        /* ON DELETE CASCADE */
);